multipart:
    max-file-size: 5120Mb
    max-request-size: 5120Mb

server:
    port: 5006
    
database:
    host: localhost
    port: 3306
    name: qrcode_demo

spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 28018
            username: admin
            password: admin
            database: qrcode
            grid-fs-database: fbs
        

logging:
    level:
        root: INFO
    file: logs/qrcode-base.log

#rest service configurations(TimeUnit: SECONDS)
connection-timeout: 10
read-timeout: 300
write-timeout: 10
